#!/bin/bash
set -eu

# Creates a configurable kali pi build

# Load functions, environment variables 
. env.sh;
. functions.sh

print_usage(){
  local usage
  usage=$(cat << 'HERE' 
Usage: 

rename an env.sh example to env.sh and modify variables

sudo ./cryptmypi.sh ARG1

ARG1 can be:
-b or build - standard build
-m or mount - decrypt and mount an image or disk
-u or unmount - unmount
-i or install - install dependencies
-mk or mkinitramfs - mounts and runs the mkinitramfs
-h or help - prints this help message
HERE
)
  print_info "$usage";
}

main(){
  print_info "$(basename "$0") started"

  trap 'trap_on_exit 0' EXIT;

  check_run_as_root;

  case $1 in
    build|-b|-B)
      #build normally
      build;
      ;;
    install|-i|-I)
      #install dependencies only
      install_dependencies;
      ;;
    mount|-m|-M)
      #mount the image only
      mount_only;
      ;;
    mkinitramfs|-mk|-MK)
      #mount and run initramfs 
      make_initramfs;
      ;;
    unmount|-u|-U)
      #unmount new image
      unmount;
      ;;
    *)
      print_usage;
      ;;
  esac
  exit 0;
}

# Run program
main "${1:-'print help'}";
