#!/bin/bash
set -eu

# Creates a configurable kali pi build

# Load functions, environment variables and dependencies
. functions.sh;
. env.sh;

print_usage(){
  local usage
  usage=$(cat << 'HERE' 
Usage: sudo ./cryptmypi.sh ARG1

BEFORE Running the script. make sure you first create your env.sh based on one of the examples
If you forget to add a variable in, the script may exit and tell you or choose a reasonable default.

ARG1 can be:
-b or build - standard build
-m or mount_only - only mount an image or disk
-u or unmount - unmount
-i or install - install dependencies
-mk or mkinitramfs - mounts and runs the mkinitramfs
-h or help - prints this help message
HERE
)
  print_info "$usage";
}

main(){
  print_info "$(basename "$0") started"

  trap 'trap_on_exit 0' EXIT;

  check_run_as_root;

  case $1 in
    build|-b)
      #build normally
      build;
      ;;
    install|-i)
      #install dependencies only
      install_dependencies;
      ;;
    mount_only|-m)
      #mount the image only
      mount_only;
      ;;
    mkinitramfs|-mk)
     #mount and run initramfs 
      make_initramfs;
      ;;
    unmount|-u)
     #unmount new image
      unmount;
      ;;
    *)
      print_usage;
      ;;
  esac
  exit 0;
}

# Run program
main "${1:-'print help'}";
