#!/bin/bash

export _USER_HOME=$(eval echo ~${SUDO_USER})
export _DNS1='1.1.1.1'
export _DNS2='8.8.8.8'
export _CPU_GOVERNOR='performance'
export _WIFI_SSID='SKYNET'
export _WIFI_PASS='JOHNCONNOR'
export _WIFI_INTERFACE='wlan0'
export _INITRAMFS_WIFI_IP=":::::${_INITRAMFS_WIFI_INTERFACE}:dhcp:${_DNS1}:${_DNS2}"
export _INITRAMFS_WIFI_DRIVERS='brcmfmac43455 brcmfmac brcmutil cfg80211 rfkill'
export _ROOTPASSWD="toor"
export _LUKSNUKEPASSWD="luks_nuke_password"
export _IODINE_DOMAIN=""
export _IODINE_PASSWORD=""
export _OPENVPN_CONFIG_ZIP="openvpn.zip"
export _KERNEL_VERSION_FILTER="l+"
export _HOSTNAME="kali"
export _BLKDEV="/dev/sda"
export _FILESYSTEM_TYPE="btrfs"
export _LUKSCIPHER="aes-xts-plain64 --key-size 512 --use-random --hash sha512 --pbkdf argon2i --iter-time 5000"
export _PKGS_TO_PURGE=""
export _PKGS_TO_INSTALL="" #tree htop ufw timeshift"
export _LUKSPASSWD=""
export _IMAGESHA="c6ceee472eb4dabf4ea895ef53c7bd28751feb44d46ce2fa3f51eb5469164c2c"
export _IMAGEURL="https://images.kali.org/arm-images/kali-linux-2020.4-rpi4-nexmon-64.img.xz"
export _SSH_LOCAL_KEYFILE="$_USER_HOME/.ssh/id_rsa"
export _SSH_PASSWORD_AUTHENTICATION="no"
export _ENCRYPTED_VOLUME_NAME="crypt-1"
export _CURRDIR=$(pwd)
export _CONFDIRNAME="${1%/}"
export _CONFDIR=${_CURRDIR}/${_CONFDIRNAME}
export _OTHER_SCRIPTS_DIR=${_CURRDIR}/other-scripts
export _BUILDDIR=${_CONFDIR}/build
export _CHROOT_ROOT=${_BUILDDIR}/root
export _FILESDIR=${_BASEDIR}/files
export _IMAGEDIR=${_FILESDIR}/images
#0 = debug messages and normal, 1 normal only
export _LOG_LEVEL=0
export _IMAGENAME=$(basename ${_IMAGEURL})
