#!/bin/sh
# This goes into /etc/initramfs-tools/hooks/enable_avahi_daemon
set -e
PREREQ=""
prereqs()
{
    echo "${PREREQ}"
}
case "${1}" in
    prereqs)
        prereqs
        exit 0
        ;;
esac

. /usr/share/initramfs-tools/hook-functions



copy_exec /usr/sbin/avahi-daemon

copy_file config /etc/avahi/avahi-daemon.conf /etc/avahi/avahi-daemon.conf
copy_file config /etc/hosts /etc/hosts
copy_file config /etc/hostname /etc/hostname
