#!/bin/sh
# This goes into /etc/initramfs-tools/hooks/enable_avahi_daemon
set -e
PREREQ=""
prereqs()
{
    echo "${PREREQ}"
}
case "${1}" in
    prereqs)
        prereqs
        exit 0
        ;;
esac

. /usr/share/initramfs-tools/hook-functions



copy_exec /usr/sbin/avahi-daemon

copy_file config /etc/initramfs-tools/avahi-daemon.conf /etc/avahi/avahi-daemon.conf
copy_file config /etc/hosts /etc/hosts
copy_file config /etc/hostname /etc/hostname
copy_file config /etc/resolv.conf /etc/resolv.conf
copy_file config /etc/nsswitch.conf /etc/nsswitch.conf
copy_file config /usr/share/doc/avahi/ssh.service /etc/avahi/services/ssh.service
echo "avahi:x:136:" >> "$DESTDIR/etc/group"
echo "avahi:x:127:136:Avahi mDNS daemon,,,:/run/avahi-daemon:/usr/sbin/nologin" >> "$DESTDIR/etc/passwd"
